export default {
    updateDetails: 0,
    testList: [],
    selectedDetails: [],
    token: localStorage.getItem('token'),
    title: 'CarPort | Заказ-наряд',
    orders: [],
    addedTypical: [],
    loader: false,
    galleryLoader: false,
    errorPage: false,
    vehid: '',
    sbarbankLink: '',
    sberBankLoader: false,
    allDetail: [],
    detailLoader: false,
    trees: [],
    sberId: '',
    errorGetOrder: false,
    infoAboutDetail: [],
    workDetailLoader: false,
    workForDetail: [],
    getInfoAboutWork: [],
    infoAboutDetail: [],
    updateWork: false,
    updateDetail: false,
    stoList: [],
    stoLoader: false,
    selSto: '',
    yourcomment: '',
    commentLoader: false,
    selectTime: {
        day: new Date(),
        time: '',
        line: 0
    },
    changeMilage: false,
    millage: '',
    millageLoader: false,
    orderAction: false,
    phyDetail: [],
    phyDetailLoader: false,
    selectPhydetail: 0,
    selectPhyDetailItem: 0,
    phyDetailNotFound: false,
    partId: 0,
    laborId: 0,
    selectPhyDetailItemInfo: '',
    selectReadlDetail: '',
    isPageLoader: true
  }