export default {
	token: localStorage.getItem('token'),
  title: 'CarPort | Ваши заказы',
  loader: false,
  orders: [],
  selectedAuto: '',
  preOrderLoader: false,
  addedTypicalDetails: [],
  preOrderCars: [],
  selnumCusPart: '',
  selectpreOrderCarId: '',
  preOrderCarsLoader: false,
  cars: [],
  typicalTree: [],
  typicalTreeLoader: false,
  carListLoader: false,
  search: '',
  pictureId: '',
  pictureLoader: false,
  detailType: 1,
  CoordSchema: [],
  notfound: false,
  serverError: false,
  VehicleRecordId: '',
  wizardForm: {
    stepOne: true,
    stepTwo: false,
    stepThree: false,
    stepFour: false
  },
  newOrder: {
    diagnostic: '',
    paintWork: '',
    optionaleq: '',
    tirefitting: '',
    comment: ''
  },
  trees: [],
  infoAboutDetail: [],
  getInfoAboutWork: [],
  vehid: '',
  detailLoader: false,
  allDetail: [],
  workDetailLoader: false,
  workForDetail: [],
  workDetailLoader: false,
  workForDetail: [],
  newCreateOrderId: '',
  partId: 0,
  laborId: 0,
  count: {
    orders: localStorage.getItem('CPcountOrders'),
    preorders: localStorage.getItem('CPcountPreOrders'),
    archive: localStorage.getItem('CPcountArchive')
  }
}